# Generated by Django 2.2.2 on 2019-07-03 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0009_auto_20190701_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='descripcion',
            field=models.TextField(default=1, verbose_name='Descripcion'),
            preserve_default=False,
        ),
    ]
