# Generated by Django 2.2.2 on 2019-07-03 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0010_auto_20190703_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
